-- SQLite
/*
CREATE TABLE Elements (
  ELEMENT_NO INTEGER NOT NULL,
  ELEMENT_CODE VARCHAR(3) PRIMARY KEY NOT NULL,
  ELEMENT_NAME VARCHAR(32) NOT NULL,
  COLOUR1 CHAR(6) NOT NULL,
  COLOUR2 CHAR(6) NOT NULL,
  COLOUR3 CHAR(6) NOT NULL,
  RADIUS DECIMAL(3) NOT NULL
);

CREATE TABLE Atoms (
  ATOM_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ELEMENT_CODE VARCHAR(3) NOT NULL,
  X DECIMAL(7, 4) NOT NULL,
  Y DECIMAL(7, 4) NOT NULL,
  Z DECIMAL(7, 4) NOT NULL,
  FOREIGN KEY (ELEMENT_CODE) REFERENCES Elements(ELEMENT_CODE)
);

CREATE TABLE Bonds (
  BOND_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  A1 INTEGER NOT NULL,
  A2 INTEGER NOT NULL,
  EPAIRS INTEGER NOT NULL
);

CREATE TABLE Molecules (
  MOLECULE_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  NAME TEXT UNIQUE NOT NULL
);

CREATE TABLE MoleculeAtom (
  MOLECULE_ID INTEGER NOT NULL,
  ATOM_ID INTEGER NOT NULL,
  PRIMARY KEY (MOLECULE_ID, ATOM_ID),
  FOREIGN KEY (MOLECULE_ID) REFERENCES Molecules(MOLECULE_ID),
  FOREIGN KEY (ATOM_ID) REFERENCES Atoms(ATOM_ID)
);

CREATE TABLE MoleculeBond (
  MOLECULE_ID INTEGER NOT NULL,
  BOND_ID INTEGER NOT NULL,
  PRIMARY KEY (MOLECULE_ID, BOND_ID),
  FOREIGN KEY (MOLECULE_ID) REFERENCES Molecules(MOLECULE_ID),
  FOREIGN KEY (BOND_ID) REFERENCES Bonds(BOND_ID)
);*/

/*
INSERT INTO Elements VALUES ('H', 1, 'Hydrogen', 'FFFFFF', '050505', '020202', 25);

INSERT INTO Elements VALUES ('C', 6, 'Carbon', '808080', '010101', '000000', 40);

INSERT INTO Elements VALUES ('N', 7, 'Nitrogen', '0000FF', '000005', '000002', 40);

INSERT INTO Elements VALUES ('O', 8, 'Oxygen', 'FF0000', '050000', '020000', 40);
*/

--INSERT INTO Molecules VALUES (1, 'Water');
--INSERT INTO Molecules VALUES (2, 'Oil');
INSERT INTO Molecules VALUES (3, 'POWER');